# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    document_directory: '/uploads/document'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'
            $document_directory: '%document_directory%'
            $app_url: '%env(APP_URL)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Listener\Doctrine\DoctrineDocumentSubscriber:
        arguments:
            $logger: '@monolog.logger.document'
        tags:
            - { name: doctrine.event_subscriber }

    App\Listener\Doctrine\DoctrineTagSubscriber:
        arguments:
            $logger: '@monolog.logger.tag'
        tags:
            - { name: doctrine.event_subscriber }

    App\Listener\DocumentSubscriber:
        arguments:
            $logger: '@monolog.logger.document'

    #Â Api
    App\Action\Document\DocumentDownload:
        public: true
